name: hci-alt-texts
channels:
  - defaults
dependencies:
  - anyio=3.5.0=py38hca03da5_0
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - boto3=1.24.28=py38hca03da5_0
  - botocore=1.27.28=py38hca03da5_0
  - bottleneck=1.3.5=py38heec5a64_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py38h1a28f6b_1002
  - ca-certificates=2022.07.19=hca03da5_0
  - certifi=2022.9.14=py38hca03da5_0
  - cffi=1.15.1=py38h22df2f2_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fftw=3.3.9=h1a28f6b_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h1a28f6b_0
  - glib=2.69.1=h98b2900_1
  - gst-plugins-base=1.14.1=hf0a386a_0
  - gstreamer=1.14.1=he09cfb7_0
  - icu=68.1=hc377ac9_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.15.2=py38hca03da5_0
  - ipython=8.4.0=py38hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38hca03da5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - jpeg=9e=h1a28f6b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py38hca03da5_0
  - jupyter_client=7.3.5=py38hca03da5_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38hca03da5_0
  - jupyter_server=1.18.1=py38hca03da5_0
  - jupyterlab=3.4.4=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0=py38hca03da5_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.2=py38hc377ac9_0
  - krb5=1.19.2=h3b8d789_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang=12.0.0=default_hc321e17_4
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.8=h1a28f6b_5
  - libedit=3.1.20210910=h1a28f6b_0
  - libffi=3.4.2=hc377ac9_4
  - libgfortran=5.0.0=11_2_0_he6877d6_26
  - libgfortran5=11.2.0=he6877d6_26
  - libiconv=1.16=h1a28f6b_2
  - libllvm12=12.0.0=h12f7ac0_4
  - libopenblas=0.3.20=hea475bc_0
  - libpng=1.6.37=hb8d0fd4_0
  - libpq=12.9=h65cfe13_3
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.4.0=had003b8_0
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libxml2=2.9.14=h8c5e841_0
  - libxslt=1.1.35=h9833966_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.3=hc377ac9_0
  - markupsafe=2.1.1=py38h1a28f6b_0
  - matplotlib=3.5.2=py38hca03da5_0
  - matplotlib-base=3.5.2=py38hc377ac9_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - mistune=0.8.4=py38h1a28f6b_1000
  - munkres=1.1.4=py_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py38hca03da5_0
  - nbconvert=6.4.4=py38hca03da5_0
  - nbformat=5.3.0=py38hca03da5_0
  - ncurses=6.3=h1a28f6b_3
  - nest-asyncio=1.5.5=py38hca03da5_0
  - notebook=6.4.12=py38hca03da5_0
  - nspr=4.33=hc377ac9_0
  - nss=3.74=h142855e_0
  - numexpr=2.8.3=py38h144ceef_0
  - openssl=1.1.1q=h1a28f6b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py38hc377ac9_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hc377ac9_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38h4d1bdd5_1
  - pip=22.1.2=py38hca03da5_0
  - ply=3.11=py38hca03da5_0
  - prometheus_client=0.14.1=py38hca03da5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38hca03da5_0
  - pyrsistent=0.18.0=py38h1a28f6b_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.13=hbdb9e5c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38hca03da5_0
  - pytz=2022.1=py38hca03da5_0
  - pyzmq=23.2.0=py38hc377ac9_0
  - qt-main=5.15.2=ha2d02b5_7
  - qt-webengine=5.15.9=h2903aaf_4
  - qtpy=2.2.0=py38hca03da5_0
  - qtwebkit=5.212=h0f11f3c_4
  - readline=8.1.2=h1a28f6b_1
  - requests=2.28.1=py38hca03da5_0
  - s3transfer=0.6.0=py38hca03da5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=63.4.1=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py38hca03da5_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.39.2=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38hca03da5_0
  - testpath=0.6.0=py38hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py38h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py38hca03da5_0
  - typing_extensions=4.3.0=py38hca03da5_0
  - urllib3=1.26.11=py38hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - websocket-client=0.58.0=py38hca03da5_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hca03da5_0
  - xz=5.2.5=h1a28f6b_1
  - zeromq=4.3.4=hc377ac9_0
  - zipp=3.8.0=py38hca03da5_0
  - zlib=1.2.12=h5a0b063_3
  - zstd=1.5.2=h8574219_0
  - pip:
    - blis==0.9.1
    - catalogue==2.0.8
    - click==8.1.3
    - confection==0.0.1
    - conllu==4.5.2
    - cymem==2.0.6
    - filelock==3.8.0
    - huggingface-hub==0.9.1
    - joblib==1.1.0
    - langcodes==3.3.0
    - murmurhash==1.0.8
    - nmslib==2.1.1
    - numpy==1.23.3
    - pathy==0.6.2
    - pip-licenses==3.5.4
    - preshed==3.0.7
    - ptable==0.9.2
    - pybind11==2.6.1
    - pydantic==1.9.2
    - pysbd==0.3.4
    - pyyaml==6.0
    - regex==2022.9.11
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - scispacy==0.5.1
    - seaborn==0.12.0
    - smart-open==5.2.1
    - spacy==3.4.1
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.4
    - thinc==8.1.1
    - thinc-apple-ops==0.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - transformers==4.21.3
    - typer==0.4.2
    - wasabi==0.10.1
prefix: /Users/lucylw/miniconda3/envs/hci-alt-texts
